[repository]
# The name of the github organization / person owner, e.g. prochain.
# Must be in lower-case letters
REGISTRY_NAME = "prochain-star-atlas"

# The name of this Pieces repository
REPOSITORY_NAME = "prochain-starflow-pieces"
REPOSITORY_LABEL = "prochain starflow pieces"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "0.1.36"
