FROM ghcr.io/prochain-star-atlas/starflow-base-piece:latest
# Install specific requirements to run OpenCV
RUN apt-get update

# Need to copy pieces source code
COPY config.toml starflow/pieces_repository/
COPY pieces starflow/pieces_repository/pieces
COPY .starflow starflow/pieces_repository/.starflow

# Install specific dependencies in starflow_env virtual environment
RUN pip install --no-cache-dir numpy==1.23.5 plotly==5.18.0
