name: Validate and organize repo, build and publish Docker images

on:
  push:
    branches:
      - main
    paths:
      - 'config.toml'

jobs:
  validate-and-organize:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Pip install packages
        run: |
          python -m pip install -U pip
          pip install --no-cache-dir starflow-py[cli]

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pip list
        run: pip list | grep starflow

      - name: Run organize and build images
        run: |
          starflow piece organize --build-images --source-url=https://github.com/${{github.repository}}

      - name: Install Tests Dependencies
        run: pip install -r requirements-tests.txt

      - name: Run tests over built images
        env:
          STARFLOW_TESTS_ENVIRONMENT: github
        run: |
          pytest --cov=pieces --cov-report=xml --cov-report=term-missing

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish images
        env:
          GHCR_USERNAME: ${{ github.actor }}
        run: starflow piece publish-images --registry-token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          GIT_STATUS=$(git status -s)
          [[ ! -z "$GIT_STATUS" ]] && git add .starflow/* && git commit -m "auto-organize" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create Release
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: starflow piece release
